-- Teremok database schema (PostgreSQL 16+; also loads into H2 in PostgreSQL mode for tests).
-- Main entity: voicings, one voice part recorded by one author.

DROP TABLE IF EXISTS votes CASCADE;
DROP TABLE IF EXISTS voicing_recordings CASCADE;
DROP TABLE IF EXISTS voicings CASCADE;
DROP TABLE IF EXISTS text_work_fragments CASCADE;
DROP TABLE IF EXISTS voice_parts CASCADE;
DROP TABLE IF EXISTS text_works CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

CREATE TABLE profiles (
    id         VARCHAR(24)              PRIMARY KEY,
    name       VARCHAR(24)              NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT profiles_id_is_lower_name CHECK (id = LOWER(name))
);

CREATE TABLE text_works (
    id       UUID         PRIMARY KEY,
    title    VARCHAR(200) NOT NULL,
    authors  VARCHAR(500) NOT NULL,
    language VARCHAR(8)   NOT NULL,
    CONSTRAINT text_works_title_not_blank CHECK (CHAR_LENGTH(TRIM(title)) > 0)
);

CREATE TABLE voice_parts (
    id           UUID         PRIMARY KEY,
    text_work_id UUID         NOT NULL REFERENCES text_works (id) ON DELETE CASCADE,
    name         VARCHAR(100) NOT NULL,
    CONSTRAINT voice_parts_unique_name UNIQUE (text_work_id, name)
);

CREATE TABLE text_work_fragments (
    id            UUID          PRIMARY KEY,
    text_work_id  UUID          NOT NULL REFERENCES text_works (id) ON DELETE CASCADE,
    number        INTEGER       NOT NULL,
    voice_part_id UUID          NOT NULL REFERENCES voice_parts (id),
    content       VARCHAR(2000) NOT NULL,
    CONSTRAINT fragments_number_positive CHECK (number > 0),
    CONSTRAINT fragments_unique_number UNIQUE (text_work_id, number)
);

CREATE TABLE voicings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voice_part_id UUID                     NOT NULL REFERENCES voice_parts (id),
    author_id     VARCHAR(24)              NOT NULL REFERENCES profiles (id),
    status        VARCHAR(16)              NOT NULL DEFAULT 'DRAFT',
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT voicings_status_known CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT voicings_published_at_set CHECK (status = 'DRAFT' OR published_at IS NOT NULL),
    CONSTRAINT voicings_one_per_author UNIQUE (voice_part_id, author_id)
);

CREATE TABLE voicing_recordings (
    voicing_id  BIGINT                   NOT NULL REFERENCES voicings (id) ON DELETE CASCADE,
    fragment_id UUID                     NOT NULL REFERENCES text_work_fragments (id),
    audio_path  VARCHAR(255)             NOT NULL,
    duration_ms INTEGER                  NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (voicing_id, fragment_id),
    CONSTRAINT recordings_unique_audio_path UNIQUE (audio_path),
    CONSTRAINT recordings_duration_valid CHECK (duration_ms >= 0 AND duration_ms <= 120000)
);

CREATE TABLE votes (
    voicing_id BIGINT                   NOT NULL REFERENCES voicings (id) ON DELETE CASCADE,
    profile_id VARCHAR(24)              NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
    kind       VARCHAR(8)               NOT NULL,
    voted_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (voicing_id, profile_id),
    CONSTRAINT votes_kind_known CHECK (kind IN ('LIKE', 'DISLIKE'))
);

CREATE INDEX voice_parts_text_work_idx ON voice_parts (text_work_id);
CREATE INDEX fragments_voice_part_idx ON text_work_fragments (voice_part_id);
CREATE INDEX voicings_author_idx ON voicings (author_id);
CREATE INDEX voicings_status_idx ON voicings (status);
CREATE INDEX votes_profile_idx ON votes (profile_id);

COMMENT ON TABLE profiles IS 'Users: id is the lower-case name';
COMMENT ON TABLE text_works IS 'Fairy tales and other texts available for voicing';
COMMENT ON TABLE voice_parts IS 'Roles (characters) of a text work';
COMMENT ON TABLE text_work_fragments IS 'Lines of a text work, numbered through the whole work from 1';
COMMENT ON TABLE voicings IS 'Main entity: one voice part recorded by one author';
COMMENT ON TABLE voicing_recordings IS 'Recorded fragments of a voicing; audio_path points to the WAV file relative to the audio directory';
COMMENT ON TABLE votes IS 'Likes and dislikes: one vote per profile per voicing';
