package space.grayt.teremok.domain;

import java.time.Instant;
import java.util.Set;

/**
 * A voicing: one voice part recorded by one author. The unit of publishing and voting. The id is
 * generated by the database, so a voicing exists only after VoicingRepository.insert.
 */
public record Voicing(long id, String textWorkId, String voicePartId, String authorId,
                      VoicingStatus status, Instant createdAt, Set<Integer> recordedFragments) {

    public Voicing {
        recordedFragments = Set.copyOf(recordedFragments);
    }

    public Voicing withStatus(VoicingStatus newStatus) {
        return new Voicing(id, textWorkId, voicePartId, authorId, newStatus, createdAt, recordedFragments);
    }

    public boolean isRecorded(int fragmentNumber) {
        return recordedFragments.contains(fragmentNumber);
    }
}
