spring:
  application:
    name: catalog-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/catalog_db}
    username: ${DATABASE_USERNAME:catalog_service}
    password: ${DATABASE_PASSWORD:catalog_service}
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        "spring.json.value.default.type": space.grayt.teremok.events.TextWorkAddedEvent
        "spring.json.trusted.packages": space.grayt.teremok.events
        "spring.json.use.type.headers": false
    listener:
      missing-topics-fatal: true

management:
  endpoints:
    web:
      exposure:
        include: health
